version: "3.3"
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: negocio
      MYSQL_ROOT_PASSWORD: fede
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: